FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt runpod

COPY shared ./shared
COPY *.py .

CMD ["python", "handler.py"]
